### ISSUE TITLE
RowTable with titleLinks=true renders links to a tiddler titled "true"

### ISSUE THREAD

**Issue by ahilliard** [OokTech/TW5-DynamicTables#1]
Great macro, thank you for sharing your work.  I have tried to get it set up, but have run into an issue where calling the RowTable macro with either

`true`
`"true"`
`titleLinks="true"`

results in a table rendered with the correct row titles but with links pointing at a tiddler named _true_ .  See attached screenshot, where the "Information Requirements" tiddler was made with 
`<<RowTable "[tag[Abstraction]] +[tagging[]]" "tags wda.infosource" true>>`

![Capture](https://user-images.githubusercontent.com/1424981/58577523-f5858280-8246-11e9-9d8e-b581f9a14bb4.JPG)

**Comment by inmysocks** [comment]
This bug should be fixed in the new version I pushed.
