### ISSUE TITLE
Handle fields containing Title Lists?

### ISSUE THREAD

**Issue by ahilliard** [OokTech/TW5-DynamicTables#2]
If you feel like doing any more work on this macro, could I please request handling fields that contain title lists?  Like the "tags" field, for example?

For example, an example tiddler in a project I'm working on has a field 'wda.infosource' that contains 

`[[Charging in km/h]] [[Planned Driving in next day - km range from this charge]] [[Demand Factor vs. building]] [[Unplug timestamp vs. rest of building]]`

running the list below through the macro:

`<<list-links filter:"[enlist{!!wda.infosource}]" emptyMessage:"* None yet! Add in the wda.infosource field">>`

produces a readable list:

- Charging in km/h
- Planned Driving in next day - km range from this charge
- Demand Factor vs. building
- Unplug timestamp vs. rest of building

Would it be possible do do something similar in a RowTable?  The improved readability would be worth sacrificing the in-place editing and/or sorting functionality.

Thank you for the consideration and for sharing this great macro.

![Capture](https://user-images.githubusercontent.com/1424981/58578079-3df17000-8248-11e9-912d-cb85c7302b6c.JPG)

**Comment by inmysocks** [comment]
This should be fixed in the new version I just pushed. If you set the wikify parameter to true than table fields are displayed as rendered wikitext which should do what you want.
